### PR TITLE
buffer window on botright

### PR DESCRIPTION
**Pull request by codcodog**
hello, i have known the plugin from  [vim awesome](http://vimawesome.com/) website, and i am using it to manage my buffers  now. 
However, when i use the plugin, i didn't find a config that opening the buffer window on botright, so i have made some changes to the source code just adding a function for window on botright.
Personally, it juse my own habit for the window on botright, and i think that way may be good. 
And more, your plugin is simple and good use, thanks for sharing.  : )

### CODE REVIEW

**Comment by troydm** [comment]
@codcodog please also add documentation for botright option you've added to doc/easybuffer.txt describing it

**Comment by codcodog** [comment]
ok, i will it.

2017-12-30 20:44 GMT+00:00 Dmitry Geurkov <notifications@github.com>:

**Comment by codcodog** [comment]
add doc for botright.

**Comment by troydm** [comment]
@codcodog thx, changes merged

**Pull request merged**
